services:
  - type: web
    name: fingrid-fcr-dashboard
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: FINGRID_API_KEY
        sync: false
      - key: PORT
        value: 3000
      - key: FINGRID_DATASET_FCR_N
        sync: false
      - key: FINGRID_DATASET_FCR_D_UP
        sync: false
      - key: FINGRID_DATASET_FCR_D_DOWN
        sync: false
      - key: FINGRID_DATASET_MFRR_CM_UP_PRICE
        sync: false
      - key: FINGRID_DATASET_MFRR_CM_DOWN_PRICE
        sync: false
